{"name": "test_login_001", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <scripts.test_login.TestLogin object at 0x000002ADC2FD4FD0>\n\n    def test_login_001(self):\n>       assert 0\nE       assert 0\n\ntest_login.py:4: AssertionError"}, "start": 1593341567773, "stop": 1593341567773, "uuid": "49f3c09f-e7d2-46cd-9a17-50fd02a3a947", "historyId": "14ed3a6f43764b7f6f01338819c9c297", "testCaseId": "61fd03ca604429f4bd9d857ac5f51598", "fullName": "scripts.test_login.TestLogin#test_login_001", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-IQ49U49"}, {"name": "thread", "value": "19216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}