{"name": "test_login_001", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <scripts.test_login.TestLogin object at 0x000001C95F4DA320>\n\n    def test_login_001(self):\n>       assert 0\nE       assert 0\n\nscripts\\test_login.py:4: AssertionError"}, "start": 1593341612825, "stop": 1593341612826, "uuid": "b11acbc8-4c9f-4170-a967-acc9a2be3b74", "historyId": "14ed3a6f43764b7f6f01338819c9c297", "testCaseId": "61fd03ca604429f4bd9d857ac5f51598", "fullName": "scripts.test_login.TestLogin#test_login_001", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-IQ49U49"}, {"name": "thread", "value": "18284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}