{"name": "test_login_002", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <scripts.test_login.TestLogin object at 0x000002513D588E48>\n\n    def test_login_002(self):\n>       assert 0\nE       assert 0\n\nscripts\\test_login.py:7: AssertionError"}, "start": 1593341587813, "stop": 1593341587814, "uuid": "ab899a1b-e855-40f5-bd15-a9f07f558144", "historyId": "51f4ddf5a78e0a1a297b81437f42fd9f", "testCaseId": "807d7923429a723b53f08fbc31059c73", "fullName": "scripts.test_login.TestLogin#test_login_002", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-IQ49U49"}, {"name": "thread", "value": "13016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}